### ISSUE TITLE
hubby repo?

### ISSUE THREAD

**Issue by rsignell-usgs** [thusoy/blag#27]
Tarjei, 
I hope it's not too annoying to contact you through an issue.

Do you think we have your approval if we asked pypi for the name "hubby"?

It appeared to us you are no longer using https://pypi.org/project/hubby/ , but perhaps you want to reserve that for a future use?

We would like to rebrand the open source project https://pypi.org/project/qhub/ to distance it from QuanSight, the company that did the initial development work.  We are hoping this will encourage more use and contributions from the community.  And since this is an infrastructure-as-code project designed to make it easy to deploy JupyterHub backed by Kubernetes on any Cloud, it seemed  "hubby" would be a great name. 

Thanks for your consideration,
Rich Signell
USGS

**Comment by thusoy** [comment]
No problem at all! Sure thing, just let me know your PyPI username and I can add you as a collaborator to hubby, then you can remove me as a maintainer and do what you want with it (delete and re-create to start with empty history most likely).

**Comment by rsignell-usgs** [comment]
Thanks so much @thusoy !!!   I'm "rsignell" on pypi.

**Comment by thusoy** [comment]
Alright, sent you an invite now, have fun. :)
